### ISSUE TITLE
Allow non-syntactic variable names.

### ISSUE THREAD

**Issue by jonovik** [tdhock/directlabels#16]
direct.label() with a ggplot breaks if a variable name contains spaces.
Such names are often useful for automatic human-friendly labeling in plots.
Small reproducible example:

```r
library(ggplot2)
library(directlabels)
mpg2 <- within(mpg, `car class` <- class)
# This works fine:
direct.label(ggplot(mpg, aes(hwy, cty, colour=class)) + geom_point())
# This fails:
direct.label(ggplot(mpg2, aes(hwy, cty, colour=`car class`)) + geom_point())
## Error in parse(text = x) : <text>:1:5: unexpected symbol
## 1: car class
##         ^
```

**Comment by tdhock** [comment]
I would be more than happy to accept a PR that fixes this, but I don't really have time to code it myself.

**Comment by tdhock** [comment]
probably around here in getData, inside of direct.label.ggplot https://github.com/tdhock/directlabels/blob/master/R/ggplot2.R#L151

if you do a PR please add your example as a new unit test. current testing code does not use testthat but feel free to add testthat as a dep if you want.
