### ISSUE TITLE
A helper function for this type of label?

### ISSUE THREAD

**Issue by kendonB** [tdhock/directlabels#18]
Snipped from a larger plot:

![image](https://user-images.githubusercontent.com/5327505/46977618-1de1c600-d129-11e8-9e1e-20595777af54.png)

The code that generates this is:

```r
myplot + 
  annotate(geom = "text", x = mydata$x[320] + 30,
         y = mydata$fit[320] - 0.1,
         label = "IV only", hjust = 0, size = 4.5, color = "orange") +
  geom_segment(aes(x = mydata$x[320], 
                   y = mydata$fit[320],
                   xend = mydata$x[320],
                   yend = mydata$fit[320] - 0.1), color = "orange") +
  geom_segment(aes(x = mydata$x[320], 
                   y = mydata$fit[320] - 0.1,
                   xend = mydata$x[320] + 25,
                   yend = mydata$fit[320] - 0.1), color = "orange")
```
These could be nicely wrapped up into a function in directlabels.

**Comment by tdhock** [comment]
hi @kendonB thanks for the idea -- sorry it has taken so long to get back to you. I would be more than happy to consider a PR if you would like to write a new Positioning Method.

**Comment by kendonB** [comment]
For any googlers, this seems like it works:

```r
tip_label <- function (x_pos, x_tip_size, y_pos, yend_pos, label, text_size = 4.5, color = "black", points_left = TRUE) {
    list(annotate(geom = "text", x = x_pos + if_else(points_left, -x_tip_size*1.1, x_tip_size*1.1),
           y = yend_pos,
           label = label, hjust = if_else(points_left, 1, 0), size = text_size, color = color),
    geom_segment(aes(x = x_pos, 
                     y = y_pos,
                     xend = x_pos,
                     yend = yend_pos), color = color),
    geom_segment(aes(x = x_pos, 
                     y = yend_pos,
                     xend = x_pos + if_else(points_left, -x_tip_size, x_tip_size),
                     yend = yend_pos), color = color))
}
```

**Comment by kendonB** [comment]
Could you give some initial guidance for making this a "positioning method"

**Comment by tdhock** [comment]
Positioning methods are described on ?apply.method https://github.com/tdhock/directlabels/blob/master/man/apply.method.Rd and there are some additional examples here http://directlabels.r-forge.r-project.org/examples.html

Basically it can be any function(d, ...) where d is your input data.frame to plot, which should output another data frame of labels to plot. You can use http://directlabels.r-forge.r-project.org/docs/utility.function/posfuns/calc.boxes.html to get the label bounding box if you want to avoid plotting labels on top of each other.

**Comment by tdhock** [comment]
to draw those segments you will need to use grid functions rather than geom_ functions, for an example with polygons see http://directlabels.r-forge.r-project.org/docs/utility.function/posfuns/draw.polygons.html
