### ISSUE TITLE
Eliminate use of :::

### ISSUE THREAD

**Issue by hadley** [tdhock/directlabels#2]
Will probably need ggplot2 to export more things

**Comment by tdhock** [comment]
while you are in the business of exporting more things from ggplot2, can you please consider exporting the following objects that we use in animint?

[ ] `scale_map`
[ ] `plot_theme`
[ ] `stairstep`
[ ] `coord_transform`
[ ] `guides_train`
[ ] `guides_merge`
[ ] `guides_geom`
[ ] `zeroGrob`
[ ] `GeomRect`
[ ] `ggname`

```
thocking@silene:~/R/animint(master)$ grep ':::' R/*.R
R/animint.R:           ggplot2:::scale_map(sc, ggplot2:::scale_breaks(sc))
R/animint.R:  theme.pars <- ggplot2:::plot_theme(meta$plot)
R/animint.R:    g.data <- plyr::ddply(g.data, "group", function(df) ggplot2:::stairstep(df))
R/animint.R:  ## Idea: use the ggplot2:::coord_transform(coords, data, scales)
R/animint.R:    ggplot2:::coord_transform(meta$plot$coord, x, y)
R/animint.R:  theme <- ggplot2:::plot_theme(plot)
R/animint.R:    ggplot2:::guides_train(scales = scales,
R/animint.R:    gdefs <- ggplot2:::guides_merge(gdefs)
R/animint.R:    gdefs <- ggplot2:::guides_geom(gdefs, layers, default_mapping)
R/animint.R:  } else (ggplot2:::zeroGrob())
R/animint.R:#' @param mb single entry from ggplot2:::guides_merge() list of legend data
R/facets.R:# The implementation here is a modified version of ggplot2:::facet_strips.
R/geoms.R:  GeomTallRect <- proto(ggplot2:::GeomRect,{
R/geoms.R:      with(ggplot2:::coord_transform(coordinates, data, scales),
R/geoms.R:           ggplot2:::ggname(.$my_name(), {
R/geoms.R:  GeomWideRect <- proto(ggplot2:::GeomRect,{
R/geoms.R:      with(ggplot2:::coord_transform(coordinates, data, scales),
R/geoms.R:           ggplot2:::ggname(.$my_name(), {
```

**Comment by hadley** [comment]
What are you using `guides_*` for ?

**Comment by tdhock** [comment]
In animint (not directlabels), we use the guides functions inside of `getLegendList` to get information about how the legends are displayed, so we can render them on the web page. Is there another way to get that information?

**Comment by hadley** [comment]
Probably not. I'm torn on whether those functions should be exported or not. On one hand, they are definitely internal functions, and what you're doing with animint is extremely risky if the ggplot2 internals changed. OTOH, ggplot2 is stable now, and it's extremely unlikely that the internal interface will ever change. 

I suspect a better approach for animint is just to use a technique that avoids the `:::` warning in R CMD check. It's no less unsafe, and avoids me having to export a random set of otherwise internal functions. The most important thing is to ensure animint has some unit tests so that if ggplot2 ever does change in a way that would break animint, I'll pick it up and let you know during the revdep check process.

**Comment by tdhock** [comment]
ok thanks for the consideration. I guess if we ever want to put animint on
cran in the future we will just copy the relevant parts of ggplot2 and
paste them into animint. (actually, we already did this for facet_strips)

**Comment by hadley** [comment]
That's not a good solution either. Instead just write your own version of `:::` that R CMD check doesn't complain about:

```R
"%:::%" <- function(p, f) {
  get(f, envir = asNamespace(p))
}
```

**Comment by cpsievert** [comment]
[I think we could try `from(pkg, obj)`](https://github.com/jeroenooms/opencpu/blob/3c4ea8e297ce5dfb57c9cf4552a0d9c4ddcf9824/teststuff/cranhacks.txt#L2)

**Comment by tdhock** [comment]
Done in new version on master.
