### ISSUE TITLE
Work when package is not attached

### ISSUE THREAD

**Issue by hadley** [tdhock/directlabels#3]
This may be a proto issue

```R
plot <- ggplot(mpg, aes(displ, hwy, colour = class)) +
  geom_point() +
  directlabels::geom_dl(aes(label = class), list("last.points",rot = 30))

plot # fails
library(proto)
plot # succeeds
```

Also ideally need to make proto just suggested, not imported (as in my PR)

**Comment by tdhock** [comment]
To be honest I have never used `geom_dl` without first doing `library(directlabels)`.

Can you explain when it is interesting or preferable to not attach?

**Comment by hadley** [comment]
Partly it's a matter of principle - you package should work regardless of whether it's attached or not.

In practice, I finding using code like above useful for teaching as it makes it very clear that `geom_dl()` isn't part of ggplot2, but is available in another package.

**Comment by tdhock** [comment]
That makes sense.
