### ISSUE TITLE
finer control of geom_dl/directlabel aesthetics?

### ISSUE THREAD

**Issue by bbolker** [tdhock/directlabels#31]
I'm trying to draw a smooth plot with coloured ribbons (i.e. `geom_smooth(..., aes(fill=g))`) and direct-label with angled boxes, but I'm running into trouble.

- `direct.label()` inherits the fill specification, so the boxes get filled in with the same colour as the text (uh-oh)
- `geom_dl` doesn't seem to handle the application of the `smooth` stat properly

I spent a while hacking around with adding `override.aes` arguments to `geom_dl`, and/or `...` arguments to `direct.label`, but so far without success ...

  thanks!

reproducible example:

```r
library(ggplot2); theme_set(theme_bw())
library(directlabels)
set.seed(101)
dd <- expand.grid(x=1:10,g=factor(1:2))
dd <- transform(dd,y =2+as.numeric(g)*x + rnorm(20,sd=4))
gg1 <- (ggplot(dd,aes(x,y,colour=g))
    + geom_smooth(alpha=0.1,formula=y~x,method="loess"))

## uncoloured ribbons: fine
direct.label(gg1,method="angled.boxes")

## coloured ribbons: 'fill' takes over the rectangle background
direct.label(gg1+aes(fill=g),method="angled.boxes")

## geom_dl() ignores the smooth stat ...
gg1 + geom_dl(method="angled.boxes", aes(label=g))

## this helps, but the positioning is still bad
gg1 + aes(fill=g) + geom_dl(method="angled.boxes", aes(label=g, x=x,y=y, colour=g), inherit.aes=FALSE)
```

**Comment by tdhock** [comment]
hi thanks for your interest and MRE.
1. the fill thing is not a bug, it's a feature! In detail your positioning method angled.boxes looks like this
```r
> angled.boxes
[[1]]
[1] "far.from.others.borders"

[[2]]
[1] "calc.boxes"

[[3]]
[1] "enlarge.box"

[[4]]
[1] "draw.rects"
```
which means it is using draw.rects at the end to draw those rectangles behind the text labels,
```r
> draw.rects
function (d, ...) 
{
    if (is.null(d$box.color)) 
        d$box.color <- "black"
    if (is.null(d$fill)) 
        d$fill <- "white"
    for (i in 1:nrow(d)) {
        with(d[i, ], grid.rect(gp = gpar(col = box.color, fill = fill), 
            vp = viewport(x, y, w, h, "cm", c(hjust, vjust), 
                angle = rot), name = "directlabels.draw.rects"))
    }
    d
}
```
if the fill column is not NULL (as when you specify fill aes) then it is used for the rect fill. to override that you can specify a constant value for that column as the first thing in your positioning method,
```r
direct.label(gg1+aes(fill=g),method=list(fill="white", "angled.boxes"))
```

2. geom_dl is not compatible with stat_smooth because they both accept a "method" parameter and ggplot2 no longer has any way to know whether to pass "method" to the stat or geom, #24 
direct.label(gg, method=something) DOES work because direct.label knows to use method with the geom_dl and NOT the stat_smooth.

**Comment by bbolker** [comment]
thank you! what I needed was the overriding trick.  I think I've *tried* to look for this, but maybe not recently enough.  If you would be willing to point me to the best documentation for this (or, say that it doesn't really exist if that's the case) that would be greatly appreciated ...

**Comment by tdhock** [comment]
From https://www.rdocumentation.org/packages/directlabels/versions/2020.6.17/topics/apply.method :
The elements of a Positioning Method list can be...a named list element is used to add or update variables in the data.frame of direct labels to plot. For example list("first.points",cex=1.5) means take only the first points of every group and then set the cex column to 1.5.
see also
http://directlabels.r-forge.r-project.org/docs/index.html
http://directlabels.r-forge.r-project.org/docs/lineplot/posfuns/angled.boxes.html
http://directlabels.r-forge.r-project.org/docs/utility.function/posfuns/draw.rects.html

**Comment by bbolker** [comment]
thank you! I had found the angled.boxes doc (and it will repay closer examination, perhaps if I restrict the scope of the `fill` aesthetic carefully I won't need the `fill="white"`).  Abusing your helpfulness slightly, I was wondering if there is a way to do *non*-angled boxes?

**Comment by tdhock** [comment]
again in the definition of draw.rects you can see that the angle parameter comes from the rot column so you could edit that.
it is assigned in http://directlabels.r-forge.r-project.org/docs/utility.function/posfuns/far.from.others.borders.html so you would have to change the rot column AFTER that, e.g.,
```r
direct.label(gg1+aes(fill=g),method=list(
  fill="white", "far.from.others.borders", rot=0, "calc.boxes", "enlarge.box", "draw.rects"))
```

**Comment by bbolker** [comment]
cool, thank you! I'll go away for a while now :-)
