### ISSUE TITLE
Error when positioning angled.boxes etc.

### ISSUE THREAD

**Issue by hg2581** [tdhock/directlabels#32]
I am trying to replicate the contour plots and using direct.labels to position labels as described in https://stackoverflow.com/questions/38154679/r-adding-legend-and-directlabels-to-ggplot2-contour-plot. However, the examples beginning with the one using "angled.boxes" result in errors such as 
rror in approx(x, y) : need at least two non-NA values to interpolate
In addition: Warning messages:
1: In regularize.values(x, y, ties, missing(ties)) :
  collapsing to unique 'x' values
2: In regularize.values(x, y, ties, missing(ties)) :
  collapsing to unique 'x' values
3: In regularize.values(x, y, ties, missing(ties)) :
  collapsing to unique 'x' values
4: In regularize.values(x, y, ties, missing(ties)) :
  collapsing to unique 'x' values
5: In regularize.values(x, y, ties, missing(ties)) :
  collapsing to unique 'x' values
6: In regularize.values(x, y, ties, missing(ties)) :
  collapsing to unique 'x' values
7: In regularize.values(x, y, ties, missing(ties)) :
  collapsing to unique 'x' values
8: In regularize.values(x, y, ties, missing(ties)) :
  collapsing to unique 'x' values
9: In regularize.values(x, y, ties, missing(ties)) :
  collapsing to unique 'x' values
10: In regularize.values(x, y, ties, missing(ties)) :
  collapsing to unique 'x' values

I am running R 3.6 under CentOS 7, the latest version available in an official repository.

**Comment by tdhock** [comment]
hi please use one of #29 instead of directlabels.
