### ISSUE TITLE
Thumbnail image to be used in ggplot2 extensions gallery

### ISSUE THREAD

**Issue by Anirban166** [tdhock/directlabels#42]
I think plots made via positioning methods like `last.qp`, `top.bumptwice` and `smart.grid` would look good, as they are the best choices. The 350x300 versions (saved manually or via ggsave) get cramped up and some of the text labels gets cropped, so I'll go with a 700x600 version of the chosen plot. Here are the ones that I like: 

1)
![chemscore](https://user-images.githubusercontent.com/30123691/123551209-700a8e80-d78e-11eb-8ce4-03c13b7fe851.png)

2)
![lars](https://user-images.githubusercontent.com/30123691/123551213-726ce880-d78e-11eb-9e5f-dbe3172757d2.png)

3)
![projectionSeconds](https://user-images.githubusercontent.com/30123691/123551217-7567d900-d78e-11eb-8607-2c02805efe0c.png)

4)![ridge](https://user-images.githubusercontent.com/30123691/123551221-77ca3300-d78e-11eb-8ba9-940fd6b441c3.png)

5)
![sd](https://user-images.githubusercontent.com/30123691/123551224-7ac52380-d78e-11eb-8a9d-95f5b3e7c728.png)

6)
![gcse](https://user-images.githubusercontent.com/30123691/123552422-b31b3080-d793-11eb-972f-584759dab385.png)

7)
![iris](https://user-images.githubusercontent.com/30123691/123552428-b7dfe480-d793-11eb-993b-191a84e49e01.png)

8)
![sg](https://user-images.githubusercontent.com/30123691/123552463-e8c01980-d793-11eb-8c9d-0342ee57362c.png)

9) 
![irise](https://user-images.githubusercontent.com/30123691/123552625-9c290e00-d794-11eb-803f-cb2d58c0bed7.png)
The 350x300 version for this one fits well:
![irise2](https://user-images.githubusercontent.com/30123691/123552627-9fbc9500-d794-11eb-8988-bab82630feee.png)

@tdhock  Among these, which would you prefer to be shown? (or let me know if I should go for something else)

Also, for the short and long descriptions, are the ones from my coding plan okay? Here is what I had for those fields:
![image](https://user-images.githubusercontent.com/30123691/123552872-ee1e6380-d795-11eb-81f4-af911939ead9.png)

Let me know the modified sentences if you would prefer something else (for this contribution, it's better to have it in your words and with a picture you prefer since you are the author of the package!)

**Comment by tdhock** [comment]
how about the lasso path plot?
```r
if(!file.exists("prostate.csv")){
  download.file(
    "https://web.stanford.edu/~hastie/ElemStatLearn/datasets/prostate.data",
    "prostate.csv")
}
prostate <- read.table("prostate.csv")
pros <- subset(prostate, train==TRUE, -train)
ycol <- which(names(pros)=="lpsa")
x <- as.matrix(pros)[, -ycol]
y <- pros[[ycol]]
fit <- lars::lars(x,y,type="lasso")
beta.mat <- scale(coef(fit),FALSE,1/fit[["normx"]])
arclength <- rowSums(abs(beta.mat))
path <- data.frame(
  arclength,
  variable=colnames(beta.mat)[as.integer(col(beta.mat))],
  standardized.coef=as.numeric(beta.mat),
  step=as.integer(row(beta.mat)))
library(ggplot2)
p <- ggplot(path,aes(arclength,standardized.coef,colour=variable))+
  geom_line(aes(group=variable))+
  ggtitle("LASSO path for prostate cancer data")+
  xlim(-1,21)
library(directlabels)
mylabels <- list(
  rot=30,
  gapply.fun({ ## figure out where the path hits 0
    d <- d[order(d$x),]
    zero <- d$y[1]
    i <- which(d$y!=zero)[1]
    if(!is.na(i)){
      just <- as.integer(d[i,"y"]>zero)
      transform(d[i-1,],hjust=just,vjust=just)
    }
  }),
  "calc.boxes",
  ## calculate how wide the tilted box is
  dl.trans(hyp=h/sin(2*pi*rot/360)),
  dl.trans(left=x-hyp/2,right=x+hyp/2),
  ## avoid collisions between tilted boxes
  function(d,...){
    solver <- qp.labels("x","left","right")
    ## apply the solver independently for top and bottom labels.
    solution.list <- list()
    for(vj in c(0,1)){
      these <- d$vjust == vj
      if(any(these)){
        one.side <- d[these,]
        solved <- solver(one.side)
        solution.list[[paste(vj)]] <- solved
      }
    }
    do.call(rbind, solution.list)
  })
dl <- direct.label(p, dl.combine("right.polygons", "mylabels"))
png("directlabels-image.png", 350, 300)
print(dl)
dev.off()
```
![directlabels-image](https://user-images.githubusercontent.com/932850/123642633-8564d480-d7f1-11eb-8625-0c0ee8bf6f5e.png)

**Comment by Anirban166** [comment]
> how about the lasso path plot?
> 
> ```r
> if(!file.exists("prostate.csv")){
>   download.file(
>     "https://web.stanford.edu/~hastie/ElemStatLearn/datasets/prostate.data",
>     "prostate.csv")
> }
> prostate <- read.table("prostate.csv")
> pros <- subset(prostate, train==TRUE, -train)
> ycol <- which(names(pros)=="lpsa")
> x <- as.matrix(pros)[, -ycol]
> y <- pros[[ycol]]
> fit <- lars::lars(x,y,type="lasso")
> beta.mat <- scale(coef(fit),FALSE,1/fit[["normx"]])
> arclength <- rowSums(abs(beta.mat))
> path <- data.frame(
>   arclength,
>   variable=colnames(beta.mat)[as.integer(col(beta.mat))],
>   standardized.coef=as.numeric(beta.mat),
>   step=as.integer(row(beta.mat)))
> library(ggplot2)
> p <- ggplot(path,aes(arclength,standardized.coef,colour=variable))+
>   geom_line(aes(group=variable))+
>   ggtitle("LASSO path for prostate cancer data")+
>   xlim(-1,21)
> library(directlabels)
> mylabels <- list(
>   rot=30,
>   gapply.fun({ ## figure out where the path hits 0
>     d <- d[order(d$x),]
>     zero <- d$y[1]
>     i <- which(d$y!=zero)[1]
>     if(!is.na(i)){
>       just <- as.integer(d[i,"y"]>zero)
>       transform(d[i-1,],hjust=just,vjust=just)
>     }
>   }),
>   "calc.boxes",
>   ## calculate how wide the tilted box is
>   dl.trans(hyp=h/sin(2*pi*rot/360)),
>   dl.trans(left=x-hyp/2,right=x+hyp/2),
>   ## avoid collisions between tilted boxes
>   function(d,...){
>     solver <- qp.labels("x","left","right")
>     ## apply the solver independently for top and bottom labels.
>     solution.list <- list()
>     for(vj in c(0,1)){
>       these <- d$vjust == vj
>       if(any(these)){
>         one.side <- d[these,]
>         solved <- solver(one.side)
>         solution.list[[paste(vj)]] <- solved
>       }
>     }
>     do.call(rbind, solution.list)
>   })
> dl <- direct.label(p, dl.combine("right.polygons", "mylabels"))
> png("directlabels-image.png", 350, 300)
> print(dl)
> dev.off()
> ```
> 
> ![directlabels-image](https://user-images.githubusercontent.com/932850/123642633-8564d480-d7f1-11eb-8625-0c0ee8bf6f5e.png)

That looks pretty awesome! 💯
Also thanks for the code, I'll send a PR right away.
