### ISSUE TITLE
working with devel version of ggplot2?

### ISSUE THREAD

**Issue by bbolker** [tdhock/directlabels#5]
Unsurprisingly, directlabels seems to fail with the devel version of ggplot.  I will dig into this myself if I get a chance, but ... ??

e.g.:
```
dd <- data.frame(x=1:10,y=1:10,f=factor(rep(1:2,each=5)))
library(ggplot2)
g0 <- ggplot(dd,aes(x,y,colour=f))+geom_point()
g0
direct.label(g0)
## Error in switch(geom, density = "top.bumptwice", line = { :  EXPR must be a length 1 vector
```
The proximal problem is that `g0$layers[[1]]$geom`  no longer has a `name` element for identifying its type ...

**Comment by tdhock** [comment]
Hey thanks for the bug report. Did you try hadley's fork from #4 ?

**Comment by tdhock** [comment]
current master works with the new ggplot2
