### ISSUE TITLE
After update to 2024.1.21, specifying "method" arg to direct.label() leads to error

### ISSUE THREAD

**Issue by scottkosty** [tdhock/directlabels#53]
Thanks a lot for all of your work on this wonderful package, Toby!

The following example used to work as expected with a previous version of directlabels, but now fails:

```
library("directlabels")
library("ggplot2")

scatter <- qplot(jitter(hwy),jitter(cty),data=mpg,colour=class,
                 main="Fuel efficiency depends on car size")
print(direct.label(scatter))
print(direct.label(scatter, "last.bumpup"))
```

I now get the following error:

```
> print(direct.label(scatter, "last.bumpup"))
Error in get(method[[1]]) : object 'last.bumpup' not found
```

I checked the NEWS file but didn't see anything that seemed relevant for why this code might be expected to fail in the new version.

**Comment by tdhock** [comment]
hi, thanks for your interest. 
sorry for the lack of mention in NEWS, but that method was removed https://github.com/tdhock/directlabels/commit/b543ce17410f039858bda666f16b9bb5fd55ca9b
please use "last.polygons" or "last.qp" instead.

**Comment by scottkosty** [comment]
Thanks a lot for the quick reply! And thanks for the suggestion, that works well.
