### ISSUE TITLE
overlapping labels for multiple levels when using `geom_dl` with `last.bumpup` method

### ISSUE THREAD

**Issue by markheckmann** [tdhock/directlabels#7]
Using  `directlabels_2015.12.16`and  `ggplot2_2.1.0` , I think there is a slight issue with `geom_dl` when using the `last.bumpup` method with multiple levels on `x`. I also describe this on [SO](http://stackoverflow.com/questions/36821601/create-vertically-non-overlapping-labels-next-to-boxplot-using-ggplot2) in section **add-on 2**:
```r
set.seed(0)
x <- data.frame(label=LETTERS[1:24], 
                g1 = c("a"),
                g2 = c("a", "b"),
                y = rnorm(24))
x$g1 <- as.factor(x$g1)
x$g2 <- as.factor(x$g2)
x$xpos1 <- as.numeric(x$g1) + .25
x$xpos2 <- as.numeric(x$g2) + .25
```

The label placement for one level is fine. 

```r
ggplot(x, aes(x=g1, y=y)) + 
  geom_boxplot(width=.4) +
  geom_point(col="blue") +
  geom_dl(aes(x=xpos1, label=label), method= "last.bumpup")
```

For two levels some label overlaps remain.

```r
ggplot(x, aes(x=g2, y=y)) + 
  geom_boxplot(width=.4) +
  geom_point(col="blue") +
  geom_dl(aes(x=xpos2, label=label), method= "last.bumpup")
```

Same for three levels...

**Comment by tdhock** [comment]
try last.qp or last.polygons instead!
